import fs from 'node:fs';
import path from 'node:path';
import { assert, repoRoot } from './harness.mjs';

const fulfillmentJs = fs.readFileSync(path.join(repoRoot, 'app/js/modules/fulfillment.js'), 'utf8');
const html = fs.readFileSync(path.join(repoRoot, 'app/SQX_Dashboard_v6.html'), 'utf8');
const productManifest = JSON.parse(fs.readFileSync(path.join(repoRoot, 'backend/sqx-edge-tool/config/product_manifest.json'), 'utf8'));

for (const exportName of [
  'fetchQueue',
  'handleAction',
  'loadSettings',
  'processRequest',
  'renderQueue',
  'saveSettings',
  'setStatus',
  'storageKey',
  'updateRequestStatus',
]) {
  assert.ok(fulfillmentJs.includes(exportName), `missing fulfillment export ${exportName}`);
}

assert.ok(fulfillmentJs.includes("SQX.registerModule('fulfillment'"));
assert.ok(fulfillmentJs.includes("suffix.indexOf('/api/') === 0"));
assert.ok(html.includes('id="fulfillment-panel"'));
assert.ok(html.includes('id="fulfillment-request-list"'));
assert.ok(html.includes('js/modules/fulfillment.js'));
assert.equal(productManifest.upgrade.checkout.status, 'approved_controlled_commercial_movement_from_m96_decision_execution_ready');
assert.ok(productManifest.upgrade.checkout.liveReadinessTool.includes('checkout_live_readiness.py'));
assert.ok(productManifest.upgrade.checkout.liveReadinessEvidenceDir.includes('checkout_live_readiness'));
assert.ok(productManifest.upgrade.checkout.commercialReleaseCandidateTool.includes('commercial_release_candidate.py'));
assert.ok(productManifest.upgrade.checkout.commercialReleaseCandidateEvidenceDir.includes('commercial_release_candidate'));
assert.ok(productManifest.upgrade.checkout.pilotPurchaseKitTool.includes('pilot_purchase_kit.py'));
assert.ok(productManifest.upgrade.checkout.pilotPurchaseKitEvidenceDir.includes('pilot_purchase_kit'));
assert.ok(productManifest.upgrade.checkout.limitedPublicLaunchTool.includes('limited_public_launch.py'));
assert.ok(productManifest.upgrade.checkout.limitedPublicLaunchEvidenceDir.includes('limited_public_launch'));
assert.equal(productManifest.upgrade.checkout.limitedPublicLaunchPolicy, 'soft_launch_first_5_sales_then_review');
assert.ok(productManifest.upgrade.checkout.postLaunchControlTool.includes('post_launch_control.py'));
assert.ok(productManifest.upgrade.checkout.postLaunchControlEvidenceDir.includes('post_launch_control'));
assert.equal(productManifest.upgrade.checkout.postLaunchControlPolicy, 'review_first_sales_before_scaling');
assert.ok(productManifest.upgrade.checkout.commercialFeedbackLoopTool.includes('commercial_feedback_loop.py'));
assert.ok(productManifest.upgrade.checkout.commercialFeedbackLoopEvidenceDir.includes('commercial_feedback_loop'));
assert.equal(productManifest.upgrade.checkout.commercialFeedbackLoopPolicy, 'classify_feedback_before_offer_changes');
assert.ok(productManifest.upgrade.checkout.publicOfferPackTool.includes('public_offer_pack.py'));
assert.ok(productManifest.upgrade.checkout.publicOfferPackEvidenceDir.includes('public_offer_pack'));
assert.equal(productManifest.upgrade.checkout.publicOfferPackPolicy, 'review_copy_faq_release_notes_before_public_page');
assert.ok(productManifest.upgrade.checkout.launchAssetsKitTool.includes('launch_assets_kit.py'));
assert.ok(productManifest.upgrade.checkout.launchAssetsKitEvidenceDir.includes('launch_assets_kit'));
assert.equal(productManifest.upgrade.checkout.launchAssetsKitPolicy, 'prepare_assets_release_draft_and_publication_checklist');
assert.ok(productManifest.upgrade.checkout.publicReleaseGateTool.includes('public_release_gate.py'));
assert.ok(productManifest.upgrade.checkout.publicReleaseGateEvidenceDir.includes('public_release_gate'));
assert.equal(productManifest.upgrade.checkout.publicReleaseGatePolicy, 'confirm_tag_release_zip_checksum_support_and_rollback');
assert.ok(productManifest.upgrade.checkout.releasePublicationRecordTool.includes('release_publication_record.py'));
assert.ok(productManifest.upgrade.checkout.releasePublicationRecordEvidenceDir.includes('release_publication_record'));
assert.equal(productManifest.upgrade.checkout.releasePublicationRecordPolicy, 'record_tag_release_asset_checksum_support_and_rollback_publication');
assert.ok(productManifest.upgrade.checkout.postReleaseMonitorTool.includes('post_release_monitor.py'));
assert.ok(productManifest.upgrade.checkout.postReleaseMonitorEvidenceDir.includes('post_release_monitor'));
assert.equal(productManifest.upgrade.checkout.postReleaseMonitorPolicy, 'monitor_incidents_activation_support_refunds_and_scale_decision');
assert.ok(productManifest.upgrade.checkout.hotfixRollbackReleaseTool.includes('hotfix_rollback_release.py'));
assert.ok(productManifest.upgrade.checkout.hotfixRollbackReleaseEvidenceDir.includes('hotfix_rollback_release'));
assert.equal(productManifest.upgrade.checkout.hotfixRollbackReleasePolicy, 'prepare_hotfix_or_rollback_release_notes_comms_and_closure_evidence');
assert.ok(productManifest.upgrade.checkout.customerSuccessRenewalTool.includes('customer_success_renewal.py'));
assert.ok(productManifest.upgrade.checkout.customerSuccessRenewalEvidenceDir.includes('customer_success_renewal'));
assert.equal(productManifest.upgrade.checkout.customerSuccessRenewalPolicy, 'track_onboarding_activation_support_renewal_and_safe_expansion');
assert.equal(productManifest.upgrade.checkout.customerCockpitEndpoint, '/api/customer-cockpit');
assert.equal(productManifest.upgrade.checkout.customerCockpitConfig, 'backend/sqx-edge-tool/config/customer_cockpit.json');
assert.equal(productManifest.upgrade.checkout.customerCockpitPolicy, 'render_redacted_operator_summary_without_license_payloads_or_raw_events');
assert.equal(productManifest.upgrade.checkout.proBuyerPackConfig, 'backend/sqx-edge-tool/config/pro_buyer_pack.json');
assert.equal(productManifest.upgrade.checkout.proBuyerPackResourceDir, 'resources/pro-buyer-pack');
assert.ok(productManifest.upgrade.checkout.proBuyerPackValidationTool.includes('pro_buyer_pack.py'));
assert.equal(productManifest.upgrade.checkout.proBuyerPackPolicy, 'ship_safe_buyer_material_without_license_payloads_private_keys_or_financial_promises');
assert.equal(productManifest.upgrade.checkout.buyerOnboardingSupportGateConfig, 'backend/sqx-edge-tool/config/buyer_onboarding_support_gate.json');
assert.equal(productManifest.upgrade.checkout.buyerOnboardingResourceDir, 'resources/pro-buyer-pack/onboarding');
assert.ok(productManifest.upgrade.checkout.buyerOnboardingSupportGateTool.includes('buyer_onboarding_support_gate.py'));
assert.ok(productManifest.upgrade.checkout.buyerOnboardingSupportGateEvidenceDir.includes('buyer_onboarding_support_gate'));
assert.equal(productManifest.upgrade.checkout.buyerOnboardingSupportGatePolicy, 'confirm_purchase_zip_license_start_here_faq_support_and_safe_claims_before_handoff');
assert.equal(productManifest.upgrade.checkout.templatePack1Config, 'backend/sqx-edge-tool/config/template_pack_1.json');
assert.equal(productManifest.upgrade.checkout.templatePack1ResourceDir, 'resources/pro-template-pack-1');
assert.ok(productManifest.upgrade.checkout.templatePack1DeliveryTool.includes('template_pack_1_delivery.py'));
assert.ok(productManifest.upgrade.checkout.templatePack1EvidenceDir.includes('template_pack_1_delivery'));
assert.equal(productManifest.upgrade.checkout.templatePack1Policy, 'deliver_as_separate_addon_zip_after_buyer_onboarding_gate_and_safe_claims_review');
assert.equal(productManifest.upgrade.checkout.templatePack1OfferConfig, 'backend/sqx-edge-tool/config/template_pack_1_offer.json');
assert.equal(productManifest.upgrade.checkout.templatePack1OfferResourceDir, 'resources/pro-template-pack-1/offer');
assert.ok(productManifest.upgrade.checkout.templatePack1OfferTool.includes('template_pack_1_offer.py'));
assert.ok(productManifest.upgrade.checkout.templatePack1OfferEvidenceDir.includes('template_pack_1_offer'));
assert.equal(productManifest.upgrade.checkout.templatePack1OfferPolicy, 'prepare_public_addon_offer_copy_faq_checkout_draft_delivery_macro_and_support_macro_before_live_checkout');
assert.equal(productManifest.upgrade.checkout.templatePack1PublicationConfig, 'backend/sqx-edge-tool/config/template_pack_1_publication.json');
assert.ok(productManifest.upgrade.checkout.templatePack1PublicationTool.includes('template_pack_1_publication.py'));
assert.ok(productManifest.upgrade.checkout.templatePack1PublicationEvidenceDir.includes('template_pack_1_publication'));
assert.equal(productManifest.upgrade.checkout.templatePack1PublicationPolicy, 'require_real_checkout_url_variant_support_email_and_rollback_before_controlled_publication');
assert.equal(productManifest.upgrade.checkout.templatePack1PurchaseDrillConfig, 'backend/sqx-edge-tool/config/template_pack_1_purchase_drill.json');
assert.ok(productManifest.upgrade.checkout.templatePack1PurchaseDrillTool.includes('template_pack_1_purchase_drill.py'));
assert.ok(productManifest.upgrade.checkout.templatePack1PurchaseDrillEvidenceDir.includes('template_pack_1_purchase_drill'));
assert.equal(productManifest.upgrade.checkout.templatePack1PurchaseDrillPolicy, 'record_controlled_addon_order_payment_delivery_support_and_refund_pause_before_scaling');
assert.equal(productManifest.upgrade.checkout.templatePack1HandoffConfig, 'backend/sqx-edge-tool/config/template_pack_1_handoff.json');
assert.ok(productManifest.upgrade.checkout.templatePack1HandoffTool.includes('template_pack_1_handoff.py'));
assert.ok(productManifest.upgrade.checkout.templatePack1HandoffEvidenceDir.includes('template_pack_1_handoff'));
assert.equal(productManifest.upgrade.checkout.templatePack1HandoffPolicy, 'confirm_delivery_support_first_value_and_scale_or_pause_decision_after_controlled_purchase');
assert.equal(productManifest.upgrade.checkout.templatePack1SalesRegisterConfig, 'backend/sqx-edge-tool/config/template_pack_1_sales_register.json');
assert.ok(productManifest.upgrade.checkout.templatePack1SalesRegisterTool.includes('template_pack_1_sales_register.py'));
assert.ok(productManifest.upgrade.checkout.templatePack1SalesRegisterEvidenceDir.includes('template_pack_1_sales_register'));
assert.equal(productManifest.upgrade.checkout.templatePack1SalesRegisterPolicy, 'track_redacted_addon_sales_delivery_support_refunds_and_scale_decision_before_more_traffic');
assert.equal(productManifest.upgrade.checkout.templatePack1FeedbackCohortConfig, 'backend/sqx-edge-tool/config/template_pack_1_feedback_cohort.json');
assert.ok(productManifest.upgrade.checkout.templatePack1FeedbackCohortTool.includes('template_pack_1_feedback_cohort.py'));
assert.ok(productManifest.upgrade.checkout.templatePack1FeedbackCohortEvidenceDir.includes('template_pack_1_feedback_cohort'));
assert.equal(productManifest.upgrade.checkout.templatePack1FeedbackCohortPolicy, 'review_redacted_buyer_feedback_support_refunds_and_positive_signals_before_scaling_or_template_pack_2');
assert.equal(productManifest.upgrade.checkout.templatePack1ActionPlanConfig, 'backend/sqx-edge-tool/config/template_pack_1_action_plan.json');
assert.ok(productManifest.upgrade.checkout.templatePack1ActionPlanTool.includes('template_pack_1_action_plan.py'));
assert.ok(productManifest.upgrade.checkout.templatePack1ActionPlanEvidenceDir.includes('template_pack_1_action_plan'));
assert.equal(productManifest.upgrade.checkout.templatePack1ActionPlanPolicy, 'convert_feedback_cohort_into_owner_priority_support_claims_distribution_and_next_phase_actions');
assert.equal(productManifest.upgrade.checkout.templatePack2SpecsConfig, 'backend/sqx-edge-tool/config/template_pack_2_specs.json');
assert.ok(productManifest.upgrade.checkout.templatePack2SpecsTool.includes('template_pack_2_specs.py'));
assert.ok(productManifest.upgrade.checkout.templatePack2SpecsEvidenceDir.includes('template_pack_2_specs'));
assert.equal(productManifest.upgrade.checkout.templatePack2SpecsPolicy, 'define_pack_2_scope_assets_presets_support_delivery_and_next_phase_before_building_resources');
assert.equal(productManifest.upgrade.checkout.templatePack2AssetsConfig, 'backend/sqx-edge-tool/config/template_pack_2_assets.json');
assert.equal(productManifest.upgrade.checkout.templatePack2ResourceDir, 'resources/pro-template-pack-2');
assert.ok(productManifest.upgrade.checkout.templatePack2AssetsTool.includes('template_pack_2_assets.py'));
assert.ok(productManifest.upgrade.checkout.templatePack2AssetsEvidenceDir.includes('template_pack_2_assets'));
assert.equal(productManifest.upgrade.checkout.templatePack2AssetsPolicy, 'deliver_initial_pack_2_assets_as_separate_addon_zip_after_specs_gate_and_safe_claims_review');
assert.equal(productManifest.upgrade.checkout.templatePack2OfferPackConfig, 'backend/sqx-edge-tool/config/template_pack_2_offer_pack.json');
assert.equal(productManifest.upgrade.checkout.templatePack2OfferPackResourceDir, 'resources/pro-template-pack-2/offer');
assert.ok(productManifest.upgrade.checkout.templatePack2OfferPackTool.includes('template_pack_2_offer_pack.py'));
assert.ok(productManifest.upgrade.checkout.templatePack2OfferPackEvidenceDir.includes('template_pack_2_offer_pack'));
assert.equal(productManifest.upgrade.checkout.templatePack2OfferPackPolicy, 'prepare_pack_2_offer_copy_faq_checkout_draft_delivery_macro_and_support_macro_before_live_checkout');
assert.equal(productManifest.upgrade.checkout.templatePack2PublicationConfig, 'backend/sqx-edge-tool/config/template_pack_2_publication.json');
assert.ok(productManifest.upgrade.checkout.templatePack2PublicationTool.includes('template_pack_2_publication.py'));
assert.ok(productManifest.upgrade.checkout.templatePack2PublicationEvidenceDir.includes('template_pack_2_publication'));
assert.equal(productManifest.upgrade.checkout.templatePack2PublicationPolicy, 'require_real_checkout_url_variant_support_rollback_and_purchase_drill_before_controlled_publication');
assert.equal(productManifest.upgrade.checkout.templatePack2PurchaseDrillConfig, 'backend/sqx-edge-tool/config/template_pack_2_purchase_drill.json');
assert.ok(productManifest.upgrade.checkout.templatePack2PurchaseDrillTool.includes('template_pack_2_purchase_drill.py'));
assert.ok(productManifest.upgrade.checkout.templatePack2PurchaseDrillEvidenceDir.includes('template_pack_2_purchase_drill'));
assert.equal(productManifest.upgrade.checkout.templatePack2PurchaseDrillPolicy, 'record_controlled_pack_2_order_payment_delivery_support_and_refund_pause_before_scaling');
assert.equal(productManifest.upgrade.checkout.templatePack2HandoffConfig, 'backend/sqx-edge-tool/config/template_pack_2_handoff.json');
assert.ok(productManifest.upgrade.checkout.templatePack2HandoffTool.includes('template_pack_2_handoff.py'));
assert.ok(productManifest.upgrade.checkout.templatePack2HandoffEvidenceDir.includes('template_pack_2_handoff'));
assert.equal(productManifest.upgrade.checkout.templatePack2HandoffPolicy, 'confirm_delivery_support_first_value_and_scale_or_pause_decision_after_controlled_pack_2_purchase');
assert.equal(productManifest.upgrade.checkout.templatePack2SalesRegisterConfig, 'backend/sqx-edge-tool/config/template_pack_2_sales_register.json');
assert.ok(productManifest.upgrade.checkout.templatePack2SalesRegisterTool.includes('template_pack_2_sales_register.py'));
assert.ok(productManifest.upgrade.checkout.templatePack2SalesRegisterEvidenceDir.includes('template_pack_2_sales_register'));
assert.equal(productManifest.upgrade.checkout.templatePack2SalesRegisterPolicy, 'track_redacted_pack_2_sales_delivery_support_refunds_and_scale_decision_before_more_traffic');
assert.equal(productManifest.upgrade.checkout.templatePack2FeedbackCohortConfig, 'backend/sqx-edge-tool/config/template_pack_2_feedback_cohort.json');
assert.ok(productManifest.upgrade.checkout.templatePack2FeedbackCohortTool.includes('template_pack_2_feedback_cohort.py'));
assert.ok(productManifest.upgrade.checkout.templatePack2FeedbackCohortEvidenceDir.includes('template_pack_2_feedback_cohort'));
assert.equal(productManifest.upgrade.checkout.templatePack2FeedbackCohortPolicy, 'review_redacted_pack_2_buyer_feedback_support_refunds_and_positive_signals_before_expanding_traffic');
assert.equal(productManifest.upgrade.checkout.buyerReadyCheckoutCloseoutConfig, 'backend/sqx-edge-tool/config/buyer_ready_checkout_closeout.json');
assert.ok(productManifest.upgrade.checkout.buyerReadyCheckoutCloseoutTool.includes('buyer_ready_checkout_closeout.py'));
assert.ok(productManifest.upgrade.checkout.buyerReadyCheckoutCloseoutEvidenceDir.includes('buyer_ready_checkout_closeout'));
assert.equal(productManifest.upgrade.checkout.buyerReadyCheckoutCloseoutPolicy, 'confirm_basic_user_checkout_release_license_support_and_rollback_before_controlled_sales');
assert.equal(productManifest.upgrade.checkout.publicBuyerPageCadenceConfig, 'backend/sqx-edge-tool/config/public_buyer_page_cadence.json');
assert.ok(productManifest.upgrade.checkout.publicBuyerPageCadenceTool.includes('public_buyer_page_cadence.py'));
assert.ok(productManifest.upgrade.checkout.publicBuyerPageCadenceEvidenceDir.includes('public_buyer_page_cadence'));
assert.equal(productManifest.upgrade.checkout.publicBuyerPageCadencePolicy, 'prepare_public_buyer_page_checklist_support_cadence_and_first_sale_operations_before_wider_distribution');
assert.equal(productManifest.upgrade.checkout.firstControlledBuyerLogConfig, 'backend/sqx-edge-tool/config/first_controlled_buyer_log.json');
assert.ok(productManifest.upgrade.checkout.firstControlledBuyerLogTool.includes('first_controlled_buyer_log.py'));
assert.ok(productManifest.upgrade.checkout.firstControlledBuyerLogEvidenceDir.includes('first_controlled_buyer_log'));
assert.equal(productManifest.upgrade.checkout.firstControlledBuyerLogPolicy, 'record_first_controlled_buyer_activation_support_feedback_and_post_sale_decision_without_personal_data');
assert.equal(productManifest.upgrade.checkout.postSaleImprovementLoopConfig, 'backend/sqx-edge-tool/config/post_sale_improvement_loop.json');
assert.ok(productManifest.upgrade.checkout.postSaleImprovementLoopTool.includes('post_sale_improvement_loop.py'));
assert.ok(productManifest.upgrade.checkout.postSaleImprovementLoopEvidenceDir.includes('post_sale_improvement_loop'));
assert.equal(productManifest.upgrade.checkout.postSaleImprovementLoopPolicy, 'convert_first_controlled_buyer_feedback_into_onboarding_support_macro_public_copy_and_safe_claim_micro_updates');
assert.equal(productManifest.upgrade.checkout.postSaleMicroUpdatesConfig, 'backend/sqx-edge-tool/config/post_sale_micro_updates.json');
assert.ok(productManifest.upgrade.checkout.postSaleMicroUpdatesTool.includes('post_sale_micro_updates.py'));
assert.ok(productManifest.upgrade.checkout.postSaleMicroUpdatesEvidenceDir.includes('post_sale_micro_updates'));
assert.equal(productManifest.upgrade.checkout.postSaleMicroUpdatesPolicy, 'verify_applied_buyer_facing_micro_updates_and_next_controlled_buyer_readiness');
assert.equal(productManifest.upgrade.checkout.nextControlledBuyerReadinessConfig, 'backend/sqx-edge-tool/config/next_controlled_buyer_readiness.json');
assert.ok(productManifest.upgrade.checkout.nextControlledBuyerReadinessTool.includes('next_controlled_buyer_readiness.py'));
assert.ok(productManifest.upgrade.checkout.nextControlledBuyerReadinessEvidenceDir.includes('next_controlled_buyer_readiness'));
assert.equal(productManifest.upgrade.checkout.nextControlledBuyerReadinessPolicy, 'confirm_single_private_buyer_slot_checkout_license_delivery_support_followup_safe_claims_and_pause_rule');
assert.equal(productManifest.upgrade.checkout.nextControlledBuyerOutcomeConfig, 'backend/sqx-edge-tool/config/next_controlled_buyer_outcome.json');
assert.ok(productManifest.upgrade.checkout.nextControlledBuyerOutcomeTool.includes('next_controlled_buyer_outcome.py'));
assert.ok(productManifest.upgrade.checkout.nextControlledBuyerOutcomeEvidenceDir.includes('next_controlled_buyer_outcome'));
assert.equal(productManifest.upgrade.checkout.nextControlledBuyerOutcomePolicy, 'record_redacted_controlled_buyer_result_activation_first_value_support_refund_claims_and_next_distribution_decision');
assert.equal(productManifest.upgrade.checkout.controlledDistributionStepConfig, 'backend/sqx-edge-tool/config/controlled_distribution_step.json');
assert.ok(productManifest.upgrade.checkout.controlledDistributionStepTool.includes('controlled_distribution_step.py'));
assert.ok(productManifest.upgrade.checkout.controlledDistributionStepEvidenceDir.includes('controlled_distribution_step'));
assert.equal(productManifest.upgrade.checkout.controlledDistributionStepPolicy, 'execute_selected_m71_decision_as_tiny_reversible_distribution_step');
assert.equal(productManifest.upgrade.checkout.controlledDistributionReviewConfig, 'backend/sqx-edge-tool/config/controlled_distribution_review.json');
assert.ok(productManifest.upgrade.checkout.controlledDistributionReviewTool.includes('controlled_distribution_review.py'));
assert.ok(productManifest.upgrade.checkout.controlledDistributionReviewEvidenceDir.includes('controlled_distribution_review'));
assert.equal(productManifest.upgrade.checkout.controlledDistributionReviewPolicy, 'review_m72_evidence_before_repeating_holding_pausing_or_preparing_next_buyer_facing_asset');
assert.equal(productManifest.upgrade.checkout.nextBuyerFacingAssetConfig, 'backend/sqx-edge-tool/config/next_buyer_facing_asset.json');
assert.ok(productManifest.upgrade.checkout.nextBuyerFacingAssetTool.includes('next_buyer_facing_asset.py'));
assert.ok(productManifest.upgrade.checkout.nextBuyerFacingAssetEvidenceDir.includes('next_buyer_facing_asset'));
assert.equal(productManifest.upgrade.checkout.nextBuyerFacingAssetPolicy, 'prepare_one_small_buyer_facing_asset_for_private_review_only_after_m73');
assert.equal(productManifest.upgrade.checkout.privateAssetReviewConfig, 'backend/sqx-edge-tool/config/private_asset_review.json');
assert.ok(productManifest.upgrade.checkout.privateAssetReviewTool.includes('private_asset_review.py'));
assert.ok(productManifest.upgrade.checkout.privateAssetReviewEvidenceDir.includes('private_asset_review'));
assert.equal(productManifest.upgrade.checkout.privateAssetReviewPolicy, 'approve_asset_for_controlled_publication_only_after_private_review_safe_claims_support_release_notes_and_rollback');
assert.equal(productManifest.upgrade.checkout.controlledPublicationGateConfig, 'backend/sqx-edge-tool/config/controlled_publication_gate.json');
assert.ok(productManifest.upgrade.checkout.controlledPublicationGateTool.includes('controlled_publication_gate.py'));
assert.ok(productManifest.upgrade.checkout.controlledPublicationGateEvidenceDir.includes('controlled_publication_gate'));
assert.equal(productManifest.upgrade.checkout.controlledPublicationGatePolicy, 'prepare_controlled_publication_only_after_private_asset_review_support_safe_claims_release_notes_rollback_and_pause_rule_are_ready');
assert.equal(productManifest.upgrade.checkout.limitedPublicationDraftConfig, 'backend/sqx-edge-tool/config/limited_publication_draft.json');
assert.ok(productManifest.upgrade.checkout.limitedPublicationDraftTool.includes('limited_publication_draft.py'));
assert.ok(productManifest.upgrade.checkout.limitedPublicationDraftEvidenceDir.includes('limited_publication_draft'));
assert.equal(productManifest.upgrade.checkout.limitedPublicationDraftPolicy, 'prepare_limited_publication_copy_for_operator_review_only_after_m76_support_safe_claims_rollback_pause_rule_and_channel_limits_are_ready');
assert.equal(productManifest.upgrade.checkout.operatorPublicationReviewConfig, 'backend/sqx-edge-tool/config/operator_publication_review.json');
assert.ok(productManifest.upgrade.checkout.operatorPublicationReviewTool.includes('operator_publication_review.py'));
assert.ok(productManifest.upgrade.checkout.operatorPublicationReviewEvidenceDir.includes('operator_publication_review'));
assert.equal(productManifest.upgrade.checkout.operatorPublicationReviewPolicy, 'approve_manual_limited_publication_only_after_human_review_safe_copy_support_rollback_pause_rule_channel_limit_and_basic_user_flow_are_ready');
assert.equal(productManifest.upgrade.checkout.manualLimitedPublicationRecordConfig, 'backend/sqx-edge-tool/config/manual_limited_publication_record.json');
assert.ok(productManifest.upgrade.checkout.manualLimitedPublicationRecordTool.includes('manual_limited_publication_record.py'));
assert.ok(productManifest.upgrade.checkout.manualLimitedPublicationRecordEvidenceDir.includes('manual_limited_publication_record'));
assert.equal(productManifest.upgrade.checkout.manualLimitedPublicationRecordPolicy, 'record_manual_limited_publication_only_after_m78_approval_support_rollback_pause_rule_monitoring_and_redacted_channel_evidence_are_ready');
assert.equal(productManifest.upgrade.checkout.manualPublicationMonitorConfig, 'backend/sqx-edge-tool/config/manual_publication_monitor.json');
assert.ok(productManifest.upgrade.checkout.manualPublicationMonitorTool.includes('manual_publication_monitor.py'));
assert.ok(productManifest.upgrade.checkout.manualPublicationMonitorEvidenceDir.includes('manual_publication_monitor'));
assert.equal(productManifest.upgrade.checkout.manualPublicationMonitorPolicy, 'monitor_manual_limited_publication_before_any_traffic_expansion_and_block_scaling_when_support_claims_refunds_or_incidents_are_unresolved');
assert.equal(productManifest.upgrade.checkout.controlledTrafficExpansionReviewConfig, 'backend/sqx-edge-tool/config/controlled_traffic_expansion_review.json');
assert.ok(productManifest.upgrade.checkout.controlledTrafficExpansionReviewTool.includes('controlled_traffic_expansion_review.py'));
assert.ok(productManifest.upgrade.checkout.controlledTrafficExpansionReviewEvidenceDir.includes('controlled_traffic_expansion_review'));
assert.equal(productManifest.upgrade.checkout.controlledTrafficExpansionReviewPolicy, 'approve_only_tiny_controlled_traffic_expansion_after_m80_monitoring_support_claims_refunds_incidents_rollback_and_pause_rule_are_clean');
assert.equal(productManifest.upgrade.checkout.controlledTrafficExpansionStepConfig, 'backend/sqx-edge-tool/config/controlled_traffic_expansion_step.json');
assert.ok(productManifest.upgrade.checkout.controlledTrafficExpansionStepTool.includes('controlled_traffic_expansion_step.py'));
assert.ok(productManifest.upgrade.checkout.controlledTrafficExpansionStepEvidenceDir.includes('controlled_traffic_expansion_step'));
assert.equal(productManifest.upgrade.checkout.controlledTrafficExpansionStepPolicy, 'execute_only_one_tiny_reversible_traffic_step_after_m81_go_with_support_rollback_pause_rule_and_safe_claims_confirmed');
assert.equal(productManifest.upgrade.checkout.controlledTrafficExpansionMonitorConfig, 'backend/sqx-edge-tool/config/controlled_traffic_expansion_monitor.json');
assert.ok(productManifest.upgrade.checkout.controlledTrafficExpansionMonitorTool.includes('controlled_traffic_expansion_monitor.py'));
assert.ok(productManifest.upgrade.checkout.controlledTrafficExpansionMonitorEvidenceDir.includes('controlled_traffic_expansion_monitor'));
assert.equal(productManifest.upgrade.checkout.controlledTrafficExpansionMonitorPolicy, 'monitor_m82_tiny_step_before_repeating_pausing_or_widening_again');
assert.equal(productManifest.upgrade.checkout.controlledTrafficExpansionDecisionConfig, 'backend/sqx-edge-tool/config/controlled_traffic_expansion_decision.json');
assert.ok(productManifest.upgrade.checkout.controlledTrafficExpansionDecisionTool.includes('controlled_traffic_expansion_decision.py'));
assert.ok(productManifest.upgrade.checkout.controlledTrafficExpansionDecisionEvidenceDir.includes('controlled_traffic_expansion_decision'));
assert.equal(productManifest.upgrade.checkout.controlledTrafficExpansionDecisionPolicy, 'convert_m83_monitor_evidence_into_one_small_operator_decision_without_automatic_traffic_checkout_or_license_actions');
assert.equal(productManifest.upgrade.checkout.controlledTrafficExpansionExecutionConfig, 'backend/sqx-edge-tool/config/controlled_traffic_expansion_execution.json');
assert.ok(productManifest.upgrade.checkout.controlledTrafficExpansionExecutionTool.includes('controlled_traffic_expansion_execution.py'));
assert.ok(productManifest.upgrade.checkout.controlledTrafficExpansionExecutionEvidenceDir.includes('controlled_traffic_expansion_execution'));
assert.equal(productManifest.upgrade.checkout.controlledTrafficExpansionExecutionPolicy, 'record_only_the_manual_m84_approved_action_without_automatic_traffic_checkout_email_or_license_execution');
assert.equal(productManifest.upgrade.checkout.controlledTrafficExpansionExecutionMonitorConfig, 'backend/sqx-edge-tool/config/controlled_traffic_expansion_execution_monitor.json');
assert.ok(productManifest.upgrade.checkout.controlledTrafficExpansionExecutionMonitorTool.includes('controlled_traffic_expansion_execution_monitor.py'));
assert.ok(productManifest.upgrade.checkout.controlledTrafficExpansionExecutionMonitorEvidenceDir.includes('controlled_traffic_expansion_execution_monitor'));
assert.equal(productManifest.upgrade.checkout.controlledTrafficExpansionExecutionMonitorPolicy, 'monitor_m85_execution_result_before_any_further_traffic_or_commercial_movement');
assert.equal(productManifest.upgrade.checkout.controlledCommercialNextMovementConfig, 'backend/sqx-edge-tool/config/controlled_commercial_next_movement.json');
assert.ok(productManifest.upgrade.checkout.controlledCommercialNextMovementTool.includes('controlled_commercial_next_movement.py'));
assert.ok(productManifest.upgrade.checkout.controlledCommercialNextMovementEvidenceDir.includes('controlled_commercial_next_movement'));
assert.equal(productManifest.upgrade.checkout.controlledCommercialNextMovementPolicy, 'decide_next_controlled_commercial_movement_from_m86_evidence_without_automatic_traffic_checkout_email_or_license_actions');
assert.equal(productManifest.upgrade.checkout.controlledCommercialNextMovementExecutionConfig, 'backend/sqx-edge-tool/config/controlled_commercial_next_movement_execution.json');
assert.ok(productManifest.upgrade.checkout.controlledCommercialNextMovementExecutionTool.includes('controlled_commercial_next_movement_execution.py'));
assert.ok(productManifest.upgrade.checkout.controlledCommercialNextMovementExecutionEvidenceDir.includes('controlled_commercial_next_movement_execution'));
assert.equal(productManifest.upgrade.checkout.controlledCommercialNextMovementExecutionPolicy, 'record_only_the_manual_m87_approved_movement_without_automatic_traffic_checkout_email_or_license_execution');
assert.equal(productManifest.upgrade.checkout.controlledCommercialNextMovementExecutionMonitorConfig, 'backend/sqx-edge-tool/config/controlled_commercial_next_movement_execution_monitor.json');
assert.ok(productManifest.upgrade.checkout.controlledCommercialNextMovementExecutionMonitorTool.includes('controlled_commercial_next_movement_execution_monitor.py'));
assert.ok(productManifest.upgrade.checkout.controlledCommercialNextMovementExecutionMonitorEvidenceDir.includes('controlled_commercial_next_movement_execution_monitor'));
assert.equal(productManifest.upgrade.checkout.controlledCommercialNextMovementExecutionMonitorPolicy, 'monitor_m88_execution_result_before_any_broader_commercial_movement');
assert.equal(productManifest.upgrade.checkout.nextControlledCommercialMovementDecisionConfig, 'backend/sqx-edge-tool/config/next_controlled_commercial_movement_decision.json');
assert.ok(productManifest.upgrade.checkout.nextControlledCommercialMovementDecisionTool.includes('next_controlled_commercial_movement_decision.py'));
assert.ok(productManifest.upgrade.checkout.nextControlledCommercialMovementDecisionEvidenceDir.includes('next_controlled_commercial_movement_decision'));
assert.equal(productManifest.upgrade.checkout.nextControlledCommercialMovementDecisionPolicy, 'decide_next_controlled_commercial_movement_from_m89_evidence_without_automatic_traffic_checkout_email_or_license_actions');
assert.equal(productManifest.upgrade.checkout.approvedControlledCommercialMovementExecutionConfig, 'backend/sqx-edge-tool/config/approved_controlled_commercial_movement_execution.json');
assert.ok(productManifest.upgrade.checkout.approvedControlledCommercialMovementExecutionTool.includes('approved_controlled_commercial_movement_execution.py'));
assert.ok(productManifest.upgrade.checkout.approvedControlledCommercialMovementExecutionEvidenceDir.includes('approved_controlled_commercial_movement_execution'));
assert.equal(productManifest.upgrade.checkout.approvedControlledCommercialMovementExecutionPolicy, 'record_only_the_manual_m90_approved_movement_without_automatic_traffic_checkout_email_or_license_execution');
assert.equal(productManifest.upgrade.checkout.approvedControlledCommercialMovementExecutionMonitorConfig, 'backend/sqx-edge-tool/config/approved_controlled_commercial_movement_execution_monitor.json');
assert.ok(productManifest.upgrade.checkout.approvedControlledCommercialMovementExecutionMonitorTool.includes('approved_controlled_commercial_movement_execution_monitor.py'));
assert.ok(productManifest.upgrade.checkout.approvedControlledCommercialMovementExecutionMonitorEvidenceDir.includes('approved_controlled_commercial_movement_execution_monitor'));
assert.equal(productManifest.upgrade.checkout.approvedControlledCommercialMovementExecutionMonitorPolicy, 'monitor_m91_execution_result_before_any_additional_commercial_movement');
assert.equal(productManifest.upgrade.checkout.nextControlledCommercialMovementFromM92DecisionConfig, 'backend/sqx-edge-tool/config/next_controlled_commercial_movement_from_m92_decision.json');
assert.ok(productManifest.upgrade.checkout.nextControlledCommercialMovementFromM92DecisionTool.includes('next_controlled_commercial_movement_from_m92_decision.py'));
assert.ok(productManifest.upgrade.checkout.nextControlledCommercialMovementFromM92DecisionEvidenceDir.includes('next_controlled_commercial_movement_from_m92_decision'));
assert.equal(productManifest.upgrade.checkout.nextControlledCommercialMovementFromM92DecisionPolicy, 'decide_next_controlled_commercial_movement_from_m92_evidence_without_automatic_traffic_checkout_email_or_license_actions');
assert.equal(productManifest.upgrade.checkout.approvedControlledCommercialMovementFromM93ExecutionConfig, 'backend/sqx-edge-tool/config/approved_controlled_commercial_movement_from_m93_execution.json');
assert.ok(productManifest.upgrade.checkout.approvedControlledCommercialMovementFromM93ExecutionTool.includes('approved_controlled_commercial_movement_from_m93_execution.py'));
assert.ok(productManifest.upgrade.checkout.approvedControlledCommercialMovementFromM93ExecutionEvidenceDir.includes('approved_controlled_commercial_movement_from_m93_execution'));
assert.equal(productManifest.upgrade.checkout.approvedControlledCommercialMovementFromM93ExecutionPolicy, 'record_only_the_manual_m93_approved_movement_without_automatic_traffic_checkout_email_or_license_execution');
assert.equal(productManifest.upgrade.checkout.approvedControlledCommercialMovementFromM93ExecutionMonitorConfig, 'backend/sqx-edge-tool/config/approved_controlled_commercial_movement_from_m93_execution_monitor.json');
assert.ok(productManifest.upgrade.checkout.approvedControlledCommercialMovementFromM93ExecutionMonitorTool.includes('approved_controlled_commercial_movement_from_m93_execution_monitor.py'));
assert.ok(productManifest.upgrade.checkout.approvedControlledCommercialMovementFromM93ExecutionMonitorEvidenceDir.includes('approved_controlled_commercial_movement_from_m93_execution_monitor'));
assert.equal(productManifest.upgrade.checkout.approvedControlledCommercialMovementFromM93ExecutionMonitorPolicy, 'monitor_m94_execution_result_before_any_additional_commercial_movement');
assert.equal(productManifest.upgrade.checkout.nextControlledCommercialMovementFromM95DecisionConfig, 'backend/sqx-edge-tool/config/next_controlled_commercial_movement_from_m95_decision.json');
assert.ok(productManifest.upgrade.checkout.nextControlledCommercialMovementFromM95DecisionTool.includes('next_controlled_commercial_movement_from_m95_decision.py'));
assert.ok(productManifest.upgrade.checkout.nextControlledCommercialMovementFromM95DecisionEvidenceDir.includes('next_controlled_commercial_movement_from_m95_decision'));
assert.equal(productManifest.upgrade.checkout.nextControlledCommercialMovementFromM95DecisionPolicy, 'decide_next_controlled_commercial_movement_from_m95_evidence_without_automatic_traffic_checkout_email_or_license_actions');
assert.equal(productManifest.upgrade.checkout.rollbackPolicy, 'disable_checkout_pause_webhook_pause_worker_manual_fulfillment');
assert.equal(productManifest.upgrade.checkout.automation.status, 'approved_controlled_commercial_movement_from_m96_decision_execution_ready');
assert.equal(productManifest.upgrade.checkout.automation.relayIngestEndpoint, '/api/fulfillment/relay-ingest');
assert.equal(productManifest.upgrade.checkout.automation.requestStatusEndpoint, '/api/fulfillment/request-status');
assert.equal(productManifest.upgrade.checkout.automation.retryMode, 'manual_retry_with_attempt_log');
assert.equal(productManifest.upgrade.checkout.automation.relayMode, 'trusted_remote_relay_signed_bundle');
assert.equal(productManifest.upgrade.checkout.automation.relayDispatchEndpoint, '/relay/dispatch');
assert.equal(productManifest.upgrade.checkout.automation.relayConfigCheckEndpoint, '/relay/config-check');
assert.equal(productManifest.upgrade.checkout.automation.relayObservabilityEndpoint, '/relay/observability');
assert.equal(productManifest.upgrade.checkout.automation.relaySnapshotEndpoint, '/relay/observability/snapshot');
assert.equal(productManifest.upgrade.checkout.automation.relayOperatorTokenEnv, 'SQX_RELAY_OPERATOR_TOKEN');
assert.ok(productManifest.upgrade.checkout.automation.relayWorkerScript.includes('dispatch_worker.py'));
assert.ok(productManifest.upgrade.checkout.automation.relaySimulationTool.includes('simulate_purchase_flow.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayDeploymentCheckTool.includes('deployment_check.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayStagingSmokeTool.includes('staging_smoke.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayStagingEvidenceTool.includes('staging_evidence.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderApiPreflightTool.includes('render_api_preflight.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderCredentialsHandshakeTool.includes('render_credentials_handshake.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderStagingGateTool.includes('render_staging_gate.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderStagingApplyGateTool.includes('render_staging_apply_gate.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderStagingPurchaseDrillTool.includes('render_staging_purchase_drill.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderStagingLaunchPackTool.includes('render_staging_launch_pack.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderStagingSecretsKitTool.includes('render_staging_secrets_kit.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayLocalIngestTunnelCheckTool.includes('local_ingest_tunnel_check.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayLocalIngestTunnelLauncherTool.includes('local_ingest_tunnel_launcher.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayLocalIngestStagingSessionTool.includes('local_ingest_staging_session.py'));
assert.ok(productManifest.upgrade.checkout.automation.relayLocalIngestRenderHandoffTool.includes('local_ingest_render_handoff.py'));
assert.equal(productManifest.upgrade.checkout.automation.relayRenderCredentialPolicy, 'api_key_only_no_account_password');
assert.ok(productManifest.upgrade.checkout.automation.relayRenderPreflightEvidenceDir.includes('render_preflight_evidence'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderStagingGateEvidenceDir.includes('render_staging_gate'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderStagingApplyGateEvidenceDir.includes('render_staging_apply_gate'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderStagingPurchaseDrillEvidenceDir.includes('render_staging_purchase_drill'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderStagingLaunchPackEvidenceDir.includes('render_staging_launch_pack'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderStagingSecretsKitEvidenceDir.includes('render_staging_secrets_kit'));
assert.ok(productManifest.upgrade.checkout.automation.relayLocalIngestTunnelCheckEvidenceDir.includes('local_ingest_tunnel_check'));
assert.ok(productManifest.upgrade.checkout.automation.relayLocalIngestTunnelLaunchEvidenceDir.includes('local_ingest_tunnel_launch'));
assert.ok(productManifest.upgrade.checkout.automation.relayLocalIngestStagingSessionEvidenceDir.includes('local_ingest_staging_session'));
assert.ok(productManifest.upgrade.checkout.automation.relayLocalIngestRenderHandoffEvidenceDir.includes('local_ingest_render_handoff'));
assert.ok(productManifest.upgrade.checkout.automation.relayStagingEnvExample.includes('.env.staging.example'));
assert.equal(productManifest.upgrade.checkout.automation.relayRecommendedStagingProvider, 'render');
assert.ok(productManifest.upgrade.checkout.automation.relayDockerfile.includes('Dockerfile'));
assert.ok(productManifest.upgrade.checkout.automation.relayDeploymentTargets.includes('docker'));
assert.ok(productManifest.upgrade.checkout.automation.relayRenderStagingBlueprint.includes('render.staging.yaml.example'));
assert.ok(productManifest.upgrade.checkout.automation.relayStagingChecks.includes('/relay/webhook/lemon'));
assert.ok(productManifest.upgrade.checkout.automation.relayStagingChecks.includes('render_blueprint_validation'));
assert.ok(productManifest.upgrade.checkout.automation.relayRequiredProductionSecrets.includes('SQX_RELAY_OPERATOR_TOKEN'));
assert.ok(productManifest.upgrade.checkout.automation.requestStatuses.includes('failed'));
assert.ok(productManifest.upgrade.checkout.automation.operatorPanelEnabled);

console.log('fulfillment contracts ok');
