import './contracts/core_strategy_contracts.mjs';
import './contracts/app_config_contracts.mjs';
import './contracts/formatters_domain_contracts.mjs';
import './contracts/storage_ui_contracts.mjs';
import './contracts/modal_trace_contracts.mjs';
import './contracts/state_backup_contracts.mjs';
import './contracts/remote_state_contracts.mjs';
import './contracts/license_contracts.mjs';
import './contracts/fulfillment_contracts.mjs';
import './contracts/customer_cockpit_contracts.mjs';
import './contracts/support_contracts.mjs';
import './contracts/mtf_evidence_contracts.mjs';
import './contracts/champion_challenger_core_contracts.mjs';
import './contracts/champion_challenger_regime_contracts.mjs';
import './contracts/champion_challenger_ui_contracts.mjs';
import './contracts/strategy_builder_contracts.mjs';
import './contracts/renderers_charts_contracts.mjs';
import './contracts/strategies_granular_contracts.mjs';
import './contracts/ui_home_workflow_contracts.mjs';
import './contracts/home_workflow_granular_contracts.mjs';
import './contracts/edge_factory_contracts.mjs';
import './contracts/view_creator_contracts.mjs';
import './contracts/exit_policy_contracts.mjs';
import './contracts/template_maker_contracts.mjs';
import './contracts/project_generator_contracts.mjs';
import './contracts/project_generator_boundaries_contracts.mjs';

console.log('module contracts ok');
