from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from core.sqx144_mt5_instrument_parity import (
    SQX144_MT5_INSTRUMENT_PARITY_VERSION,
    GateError,
    apply_payload,
    audit_payload,
    backup_payload,
    build_plan,
    normalize_mt5_symbol_to_sqx,
    parse_mt5_xml,
    rollback_payload,
    verify_payload,
)


SAMPLE_XML = """<?xml version="1.0" encoding="UTF-8"?>
<Instruments>
<InstrumentInfo instrument="USDJPY_Darwinex" description="Generated by SQXInfoScript" tickSize="0.010" tickStep="0.001" tickValueInMoney="0.0" dateFrom="0" dateTo="0" rows="0" totalDays="0" defaultSpread="0.700" defaultSlippage="0.0" decimals="3" commissions="" pointValue="624.93" dataType="4" recognizedFromOrders="false" alias="USDJPY_Darwinex" exchange="" country="" sector="" swap="&lt;Swap use=&quot;true&quot; type=&quot;money&quot; long=&quot;5.37&quot; short=&quot;-11.50&quot; tripleSwapOn=&quot;WEDNESDAY&quot;/&gt;" orderSizeMultiplier="1.0" orderSizeStep="0.01"/>
</Instruments>
"""


def _write_project(root: Path, db: Path) -> Path:
    config_dir = root / "backend" / "sqx-edge-tool"
    config_dir.mkdir(parents=True)
    (config_dir / "config.json").write_text(
        json.dumps({
            "sqx_path": "C:/BOTS/Versiones/SQX_144_Full",
            "sqx_data_db": str(db),
            "sqx_projects_dir": "C:/BOTS/Versiones/SQX_144_Full/user/projects",
            "sqx_host_profile": "sqx144_full",
            "darwinex_suffix": "_darwinex",
        }),
        encoding="utf-8",
    )
    return root


def _write_xml(path: Path, text: str = SAMPLE_XML) -> Path:
    path.write_text(text, encoding="utf-8")
    return path


def _write_db(path: Path) -> Path:
    conn = sqlite3.connect(path)
    try:
        conn.executescript(
            """
            CREATE TABLE BROKER (ID INTEGER, NAME TEXT, POSTFIX TEXT, DESC TEXT);
            CREATE TABLE DATA (
              SYMBOL TEXT,
              INSTRUMENT TEXT,
              TIMEFRAME TEXT,
              SOURCE INTEGER,
              BROKER_ID INTEGER,
              ROWS INTEGER,
              DATEFROM INTEGER,
              DATETO INTEGER
            );
            CREATE TABLE INSTRUMENTS (
              INSTRUMENT TEXT PRIMARY KEY,
              DESCRIPTION TEXT,
              POINTVALUE REAL,
              TICKSIZE REAL,
              TICKSTEP REAL,
              DEFAULTSPREAD REAL,
              COMMISSIONS TEXT,
              DATATYPE INTEGER,
              EXCHANGE TEXT,
              COUNTRY TEXT,
              SECTOR TEXT,
              DEFAULTSLIPPAGE REAL,
              SWAP TEXT,
              ORDERSIZEMULTIPLIER REAL,
              ORDERSIZESTEP REAL,
              BROKER_ID INTEGER,
              MIN_DISTANCE REAL
            );
            """
        )
        conn.execute(
            "INSERT INTO BROKER (ID, NAME, POSTFIX, DESC) VALUES (?, ?, ?, ?)",
            (4, "Darwinex", "_darwinex", "Darwinex CFDs"),
        )
        conn.execute(
            """
            INSERT INTO DATA (SYMBOL, INSTRUMENT, TIMEFRAME, SOURCE, BROKER_ID, ROWS, DATEFROM, DATETO)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            ("USDJPY_darwinex", "USDJPY_darwinex", "TICK", 4, 4, 1000, 20200101, 20260608),
        )
        conn.execute(
            """
            INSERT INTO INSTRUMENTS (
              INSTRUMENT, DESCRIPTION, POINTVALUE, TICKSIZE, TICKSTEP, DEFAULTSPREAD,
              COMMISSIONS, DATATYPE, EXCHANGE, COUNTRY, SECTOR, DEFAULTSLIPPAGE, SWAP,
              ORDERSIZEMULTIPLIER, ORDERSIZESTEP, BROKER_ID, MIN_DISTANCE
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                "USDJPY_darwinex",
                "USDJPY Darwinex",
                627.0,
                0.01,
                0.001,
                1.0,
                '<Method type="SizeBased"><Param>5</Param></Method>',
                3,
                "",
                "",
                "",
                0.0,
                '<Swap use="true" type="money" long="5.34" short="-11.5" tripleSwapOn="WEDNESDAY" rolloutHour="23:00" />',
                1.0,
                0.01,
                4,
                0.0,
            ),
        )
        conn.commit()
    finally:
        conn.close()
    return path


def _row(db: Path) -> dict[str, object]:
    conn = sqlite3.connect(db)
    conn.row_factory = sqlite3.Row
    try:
        return dict(conn.execute("SELECT * FROM INSTRUMENTS WHERE INSTRUMENT = 'USDJPY_darwinex'").fetchone())
    finally:
        conn.close()


def test_parser_normalizes_darwinex_symbol_and_ignores_empty_commission(tmp_path):
    xml = _write_xml(tmp_path / "InstrumentInfo_USDJPY_Darwinex.xml")

    parsed = parse_mt5_xml(xml)
    instrument = parsed["instruments"][0]

    assert parsed["xmlHash"]
    assert normalize_mt5_symbol_to_sqx("USDJPY_Darwinex") == "USDJPY_darwinex"
    assert instrument.target_instrument == "USDJPY_darwinex"
    assert instrument.proposed_values()["POINTVALUE"] == 624.93
    assert "COMMISSIONS" not in instrument.proposed_values()
    assert "empty_mt5_commissions_ignored" in instrument.warnings


def test_parser_rejects_entities_unknown_attrs_duplicates_and_bad_numerics(tmp_path):
    with_entities = _write_xml(tmp_path / "entity.xml", "<!DOCTYPE x [<!ENTITY e SYSTEM 'file:///x'>]><Instruments />")
    try:
        parse_mt5_xml(with_entities)
        raise AssertionError("expected GateError")
    except GateError as exc:
        assert exc.code == "xml_external_entities_rejected"

    unknown = _write_xml(tmp_path / "unknown.xml", SAMPLE_XML.replace('orderSizeStep="0.01"', 'orderSizeStep="0.01" surprise="1"'))
    try:
        parse_mt5_xml(unknown)
        raise AssertionError("expected GateError")
    except GateError as exc:
        assert exc.code == "unknown_instrumentinfo_attr"

    instrument_node = SAMPLE_XML.split("<InstrumentInfo", 1)[1].split("</Instruments>", 1)[0]
    duplicate = _write_xml(
        tmp_path / "duplicate.xml",
        f'<?xml version="1.0" encoding="UTF-8"?><Instruments><InstrumentInfo{instrument_node}<InstrumentInfo{instrument_node}</Instruments>',
    )
    try:
        parse_mt5_xml(duplicate)
        raise AssertionError("expected GateError")
    except GateError as exc:
        assert exc.code == "duplicate_normalized_symbol"

    bad_numeric = _write_xml(tmp_path / "bad.xml", SAMPLE_XML.replace('tickSize="0.010"', 'tickSize="-0.010"'))
    try:
        parse_mt5_xml(bad_numeric)
        raise AssertionError("expected GateError")
    except GateError as exc:
        assert exc.code == "invalid_numeric"


def test_plan_reports_only_approved_instrument_changes(tmp_path):
    db = _write_db(tmp_path / "data.db")
    root = _write_project(tmp_path / "repo", db)
    xml = _write_xml(tmp_path / "InstrumentInfo_USDJPY_Darwinex.xml")

    plan = build_plan(root, xml_path=xml, db_path=db, target_instrument="USDJPY_darwinex", backup_id="backup1")

    assert plan["version"] == SQX144_MT5_INSTRUMENT_PARITY_VERSION
    assert plan["ok"] is True
    assert plan["targetInstrument"] == "USDJPY_darwinex"
    assert plan["changes"]["POINTVALUE"] == {"old": 627.0, "new": 624.93}
    assert plan["changes"]["DEFAULTSPREAD"] == {"old": 1.0, "new": 0.7}
    assert "SWAP" in plan["changes"]
    assert "COMMISSIONS" not in plan["changes"]
    assert plan["ignored"]["COMMISSIONS"] == "empty_mt5_commissions_do_not_change_sqx"
    assert plan["ignored"]["SOURCE"] == "preserve_sqx_source_authority"
    assert plan["inverseRollbackData"]["oldValues"]["POINTVALUE"] == 627.0
    assert plan["invariants"]["brokerId"] == 4
    assert plan["invariants"]["preserveSourceHistory"] is True
    assert "backup=backup1" in plan["approvalTemplate"]
    assert "no_source_broker_history" in plan["approvalTemplate"]


def test_audit_and_verify_are_read_only_until_apply_with_exact_approval(tmp_path):
    db = _write_db(tmp_path / "data.db")
    root = _write_project(tmp_path / "repo", db)
    xml = _write_xml(tmp_path / "InstrumentInfo_USDJPY_Darwinex.xml")

    audit = audit_payload(root, xml_path=xml, db_path=db, target_instrument="USDJPY_darwinex")
    row_before = _row(db)

    assert audit["readMode"] == "sqlite_uri_mode_ro_query_only"
    assert audit["auditDiff"]["changes"]["POINTVALUE"]["new"] == 624.93
    assert _row(db) == row_before

    backup = backup_payload(root, db_path=db, process_checker=lambda: [])
    plan = build_plan(root, xml_path=xml, db_path=db, target_instrument="USDJPY_darwinex", backup_id=backup["backupId"])
    blocked = apply_payload(
        root,
        xml_path=xml,
        db_path=db,
        target_instrument="USDJPY_darwinex",
        backup_id=backup["backupId"],
        approval="wrong",
        apply=True,
        process_checker=lambda: [],
    )
    assert blocked["ok"] is False
    assert blocked["status"] == "apply_blocked_bad_approval"

    applied = apply_payload(
        root,
        xml_path=xml,
        db_path=db,
        target_instrument="USDJPY_darwinex",
        backup_id=backup["backupId"],
        approval=plan["approvalTemplate"],
        apply=True,
        process_checker=lambda: [],
    )
    row_after = _row(db)
    verify = verify_payload(root, xml_path=xml, db_path=db, target_instrument="USDJPY_darwinex")

    assert applied["ok"] is True
    assert applied["appliedColumns"] == ["DEFAULTSPREAD", "POINTVALUE", "SWAP"]
    assert row_after["POINTVALUE"] == 624.93
    assert row_after["DEFAULTSPREAD"] == 0.7
    assert row_after["COMMISSIONS"] == row_before["COMMISSIONS"]
    assert row_after["BROKER_ID"] == 4
    assert verify["status"] == "verify_passed_all_approved_fields_match"


def test_apply_blocks_when_sqx_processes_are_present(tmp_path):
    db = _write_db(tmp_path / "data.db")
    root = _write_project(tmp_path / "repo", db)
    xml = _write_xml(tmp_path / "InstrumentInfo_USDJPY_Darwinex.xml")

    try:
        apply_payload(
            root,
            xml_path=xml,
            db_path=db,
            target_instrument="USDJPY_darwinex",
            backup_id="missing",
            approval="irrelevant",
            apply=True,
            process_checker=lambda: [{"processName": "StrategyQuantX", "pid": 123}],
        )
        raise AssertionError("expected GateError")
    except GateError as exc:
        assert exc.code == "sqx_processes_must_be_zero"


def test_rollback_restores_known_phase_backup(tmp_path):
    db = _write_db(tmp_path / "data.db")
    root = _write_project(tmp_path / "repo", db)
    xml = _write_xml(tmp_path / "InstrumentInfo_USDJPY_Darwinex.xml")
    backup = backup_payload(root, db_path=db, process_checker=lambda: [])
    plan = build_plan(root, xml_path=xml, db_path=db, target_instrument="USDJPY_darwinex", backup_id=backup["backupId"])

    applied = apply_payload(
        root,
        xml_path=xml,
        db_path=db,
        target_instrument="USDJPY_darwinex",
        backup_id=backup["backupId"],
        approval=plan["approvalTemplate"],
        apply=True,
        process_checker=lambda: [],
    )
    assert applied["ok"] is True

    rollback = rollback_payload(root, backup_id=backup["backupId"], db_path=db, process_checker=lambda: [])

    assert rollback["status"] == "rollback_restored_known_phase_backup"
    assert _row(db)["POINTVALUE"] == 627.0
